[package]
name = "deja-q"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }
clap = { version = "4.1", features = ["derive"] }
serde = "1.0"
postcard = { version = "1.0", features = ["alloc"] }
